In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [3]:
a.shape


(3,)

In [4]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
a2.shape

(3, 3)

In [36]:
a2[1,2]

6

In [7]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.arange(0,60,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
a3=np.array([[(1,2,3),(4,5,6)],[(7,8,9),(10,11,12)]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [15]:
a3.shape        

(2, 2, 3)

In [48]:
a3.reshape(2,3,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[ 7,  8],
        [ 9, 10],
        [11, 12]]])

In [49]:
a3[1,0,1]

8

In [50]:
a3[0,0,1]

2

In [44]:
a3[:]

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [47]:
a3[2:5]

array([], shape=(0, 2, 3), dtype=int32)

In [51]:
import pandas as pd

In [61]:
df=pd.DataFrame({"a":[4,5,6],"b":[7,8,9],"c":[10,11,12]},index=[1,2,3])  #dictionary
df

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [56]:
df.head(3)

a  b   c
1  4  7  10
2  5  8  11
3  6  9  12

In [69]:
df1=pd.DataFrame([[4,5,6],[7,8,9],[10,11,12]],index=[1,2,3],columns=['a','b','c']) #list
df1

a   b   c
1   4   5   6
2   7   8   9
3  10  11  12

In [68]:
df=pd.DataFrame({"a":[4,5,6],"b":[7,8,9],"c":[10,11,12]},index=pd.MultiIndex.from_tuples([('d',1),('d',2),('e',2)],names=['n','v'])) 
df

In [70]:
df1.sort_values('a',ascending=False)

a   b   c
3  10  11  12
2   7   8   9
1   4   5   6